### ISSUE TITLE
Some sample assets not showing in UWP

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Tooling-Windows-Submodule#100]
## Background

              Hmm, this isn't showing up on the UWP sample... (Was also having trouble seeing the code samples in the sample app). Maybe something for us to investigate outside the PR? Or is this a faux-png image that's causing issues maybe? Worked in WASDK no problem though...

_Originally posted by @michael-hawker in https://github.com/CommunityToolkit/Windows/pull/109#discussion_r1256594156_
            
## Problem
Some sample assets are not showing under the UWP in the HeaderedControl.Samples project.

WinAppSDK:
![image](https://user-images.githubusercontent.com/9384894/252454676-af6cdfd2-ec12-41eb-9e52-9a10a05148dd.png)

UWP:
![image](https://user-images.githubusercontent.com/9384894/252455192-7fe29a2a-a4ce-486a-ae53-49ac7fbd7e4c.png)

WASM:
![image](https://user-images.githubusercontent.com/9384894/252465133-d5a633cf-34e6-4934-97cd-af46fca9041e.png)

**Comment by michael-hawker** [comment]
@Arlodotexe you said JPGs are working but not PNGs or something?

**Comment by michael-hawker** [comment]
I wonder if this is because we don't automatically set the Build Action to `Content` and the Copy to Output Directory as `Copy if newer`? We should probably have a hook here like we do to automatically include XAML pages to include images, right?

**Comment by michael-hawker** [comment]
Hmm, the Converters.Samples project does that in the sample project, but it doesn't work for the BoolToVisibilityConverter sample still...
