### ISSUE TITLE
Show PackageID in Sample App Page

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Tooling-Windows-Submodule#105]
### Describe the bug

Allows us to easily detect Labs vs. non-Labs if we copy all components centrally to ship single app.

Based on this we would have the 'component name' for each sample page, meaning we can also provide a link to GitHub to the component folder.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Help us help you

Yes, but only if others can assist.

**Comment by niels9001** [comment]
![image](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/assets/9866362/512c4231-6fba-4174-85de-89e209367aab)

**Comment by michael-hawker** [comment]
Investigating this along with how we point to the Source Code folder with the 'Source' button in the sample app.

**Comment by michael-hawker** [comment]
Almost done with initial version of this. Namespace is a bit trickier...

If `<RootNamespace>` worked we could use that and grab easily from the CsProj, not sure if there's another value we could look at easily... I suppose we could define a placeholder one in each csproj...

As otherwise https://github.com/unoplatform/uno/issues/8750 is still open.

@Arlodotexe do you remember if the RootNamespace had to be unique per source project for Uno or just not equal to the assembly name of the package? Like could we set multiple to `<RootNamespace>CommunityToolkit.WinUI.ControlsRns</RootNamespace>` across multiple packages? Maybe this is a good @jeromelaban question.

As then at least we could set them all to match what the majority of namespaces are in the package and look up that in our metadata generator.

**Comment by michael-hawker** [comment]
Looking good:

![image](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/assets/24302614/0aa55d39-0aa0-4e59-8b33-5cd2cbebffd7)

And have some basic hard-coded logic for namespaces:

![image](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/assets/24302614/3c40cb4c-36ee-49d4-a886-b19f55c6efc0)
