### ISSUE TITLE
Update to .NET 8 in Wasdk

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Tooling-Windows-Submodule#164]
Add a multi-target to .NET 8 so consumers trying to use .NET 8 with WindowsAppSDK don't get the wrong .NET version.

**Comment by Arlodotexe** [comment]
Reupload of binlogs. Only Wasdk Tfms are enabled, as is `UseRidGraph`. Built the Converters source project using the msbuild cli.

[msbuild-binlog-Microsoft.WindowsAppSdk.1.4.231219000.zip](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/files/14144368/msbuild-binlog-Microsoft.WindowsAppSdk.1.4.231219000.zip)
[msbuild-binlog-Microsoft.WindowsAppSdk.1.3.230724000.zip](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/files/14144373/msbuild-binlog-Microsoft.WindowsAppSdk.1.3.230724000.zip)

**Comment by Arlodotexe** [comment]
Updated to 1.5.240205001-preview1 and still seeing the issue.

Additional binlog, built same as the others.
[msbuild-binlog-Microsoft.WindowsAppSdk.1.5.240205001-preview1.zip](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/files/14214019/msbuild-binlog-Microsoft.WindowsAppSdk.1.5.240205001-preview1.zip)

**Comment by Arlodotexe** [comment]
Binlog reupload. Same configuration as before, but with MSBuildExtras fully removed.

[msbuild-binlog-Microsoft.WindowsAppSdk.1.5.240205001-preview1-nomsbuildextras.zip](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/files/14350266/msbuild-binlog-Microsoft.WindowsAppSdk.1.5.240205001-preview1-nomsbuildextras.zip)

**Comment by Arlodotexe** [comment]
Looks like our blocker was resolved by [this commit](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/165/commits/e7e20ee052c89c004b6d18a2a8ff78dbcc8fc310), but some lingering issues still remain regarding package conflicts (see [here](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/165#issuecomment-1955098652)).

**Comment by Arlodotexe** [comment]
Had to update uno-check, but we're seeing build errors in solution generation now, possibly due to expected workloads not being installed properly. 

```
SlnGen : error : ---> (Inner Exception #28) Microsoft.Build.Exceptions.InvalidProjectFileException: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "MSBuild.Sdk.Extras/3.0.23". Exception: "System.IO.FileNotFoundException: Workload manifest microsoft.net.sdk.android: 33.0.46/7.0.100, which was specified in C:\ProgramData\dotnet\workloads\8.0.200\InstallState\default.json, was not found. Running "dotnet workload repair" may resolve this.
...
SlnGen : error : ---> (Inner Exception #34) Microsoft.Build.Exceptions.InvalidProjectFileException: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "MSBuild.Sdk.Extras/3.0.23". Exception: "System.IO.FileNotFoundException: Workload manifest microsoft.net.sdk.android: 33.0.46/7.0.100, which was specified in C:\ProgramData\dotnet\workloads\8.0.200\InstallState\default.json, was not found. Running "dotnet workload repair" may resolve this.
```

See [here](https://github.com/CommunityToolkit/Windows/actions/runs/8023508495/job/21920180606?pr=328#step:11:3639) and [here](https://github.com/CommunityToolkit/Windows/actions/runs/8023508495/job/21920180606?pr=328#step:11:4698).
