### ISSUE TITLE
Need blank registry when no components in repo

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Tooling-Windows-Submodule#22]
Discovered from #2

You can't build the all-up sample without a component as it doesn't generate a document/sample registry required for the sample app code to build.

We need a dummy stub here to be generated from the generator even if there are no components...

**Comment by Arlodotexe** [comment]
Just noticed #32 is a duplicate of this. Since we have a _lot_ of notes there, I'm closing this in favor of #32.
