### ISSUE TITLE
Changes not suppressed when switching to Uno / WinUI 3

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Tooling-Windows-Submodule#26]
## Background
In https://github.com/CommunityToolkit/Labs-Windows/pull/75, we added a [`UseUnoWinUI.ps1`](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/blob/main/MultiTarget/UseUnoWinUI.ps1) script to facilitate switching between Uno.UI and Uno.WinUI.

In #1, we moved this script into a submodule.

## Problem
After the move to a submodule, switching to WinUI 3 leaves changed files in the working tree when it didn't before.

This alone isn't an issue since the script-altered files won't get committed alongside the user's normal changes.

However, changing these files causes the parent repo to update the submodule commit hash, which can easily be committed alongside normal changes:

![image](https://user-images.githubusercontent.com/9384894/226424211-7226681b-5edf-4e07-9689-9b3aa40a9887.png)

## Solution
Suppress changes to these files again so the user cannot commit them without explicitly passing the `-allowGitChanges` flag.

**Comment by michael-hawker** [comment]
Don't we need to remove the whole removing from tracking bit? That way when we work on it here, it'll show up to commit and not be hidden?

Would that solve this issue as well? Or do we need two different behaviors depending on if it's being used in a submodule or not?

**Comment by Arlodotexe** [comment]
This is no longer planned but can be reopened at a later date if really needed. We're largely covered because most people can't push to the submodule's origin.
