### ISSUE TITLE
Update Labs.Uwp.Base.props file to use centralized versions

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Tooling-Windows-Submodule#28]
We're not using our centralized versions in the UWP Base Props file here:

https://github.com/CommunityToolkit/Labs-Windows/blob/e6389b00e04160a71e56b409e7fc8cb14ce6fcdf/common/Labs.Uwp.Base.props#L5-L9

From:

https://github.com/CommunityToolkit/Labs-Windows/blob/e6389b00e04160a71e56b409e7fc8cb14ce6fcdf/common/Labs.TargetFrameworks.props#L3

(Also, shouldn't this be Target vs. Min?)

This also appears here:

https://github.com/CommunityToolkit/Labs-Windows/blob/e6389b00e04160a71e56b409e7fc8cb14ce6fcdf/common/Labs.MultiTarget.props#L27-L36

Along with WinUI version, which we may also want to centralize (and also appears in the UWP.base.props.

Nothing urgent, but something to do later. FYI @Arlodotexe in case you have other thoughts here as well.

**Comment by Arlodotexe** [comment]
Given the recent troubles we've had around TFMs, `TargetPlatformVersion`, `TargetPlatformMinVersion` and `SupportedOSVersion` and the age of this ticket, I'd like to keep as-is for now. We've done additional organizing since this ticket was filed, and it seems to be in a good place now.
