### ISSUE TITLE
Fix NuGet pack

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Tooling-Windows-Submodule#7]
### Describe the bug

Related to CommunityToolkit/Tooling-Windows-Submodule#77

If you right-click on a library and try and `Pack` to build a NuGet package you get an error about `Icon.png` missing.

In face these resources for the icon don't exist in the repro:

https://github.com/CommunityToolkit/Labs-Windows/blob/c322845be3b1692fae6665480e9ed18ce6e4787a/Windows.Toolkit.Common.props#L12-L13

https://github.com/CommunityToolkit/Labs-Windows/blob/ed6bd23523770f34ebf6b41304dd257374fe1f04/Directory.Build.targets#L14-L19

We should be able to pack locally as well as have the proper files and icons included in the NuGet package.

@niels9001 do you know which icon asset should we use?

### Steps to reproduce

```text
1) Open an experiment or the all solution
2) Find a Library project
3) right-click on it and select 'Pack'
4) see error
```

### Expected behavior

Able to pack NuGet package

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Additional context

I guess this is ignored on the commandline?

### Help us help you

Yes, but only if others can assist.

**Comment by Nirmal4G** [comment]
@michael-hawker I don't see an `<icon/>` element in the package manifest xml file you mentioned above. There's a possibility that `<PackageIcon/>` value either clears out before it enters the NuGet pack logic or does not pass through at all. Check it with MSBuild Log Viewer.

**Comment by michael-hawker** [comment]
Thanks for pointing that out @Nirmal4G, I'll have to look. We'll also have to be aware of this issue as well: https://github.com/NuGet/Home/issues/9250 - but I'd imagine the Package Explorer app wouldn't have that same issue.

**Comment by michael-hawker** [comment]
Going to try updating the NuGet pack, iconUrl is working fine... just not `PackageIcon`...

**Comment by michael-hawker** [comment]
Confirmed this is fixed by https://github.com/CommunityToolkit/Windows/pull/174 now! 🎉🎉🎉

![image](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/assets/24302614/22db286a-da49-44c9-a428-d3b2cb610456)

![image](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/assets/24302614/87fb942c-8356-4f57-976e-8dc5eb05951d)

According [to this doc](https://learn.microsoft.com/en-us/nuget/reference/nuspec#icon) still it's recommended to specify both so that older clients can get the icon from the url. So, I'll leave that in.

Was definitely due to us using version 5.2.0... 🤦‍♂️ Filed an issue as that is the version called out in the docs as well: https://github.com/NuGet/docs.microsoft.com-nuget/issues/3124
