### ISSUE TITLE
[Gallery] Move searchbox and menu button to titlebar

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Tooling-Windows-Submodule#85]
<img width="1025" alt="image" src="https://github.com/CommunityToolkit/Tooling-Windows-Submodule/assets/9866362/97d51b86-24b8-419c-8af0-65d7fce6c9ee">

Per design guidelines, we should move the searchbox and menu button to the titlebar. This will give us some (much needed) vertical space back as well since we have a lot of menu items to show.

**Comment by Arlodotexe** [comment]
Related https://github.com/CommunityToolkit/Labs-Windows/pull/459
